# Generated by Django 4.0.1 on 2022-01-07 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('World', 'World'), ('Technology', 'Technology'), ('Environment', 'Environment'), ('Business', 'Business'), ('Education', 'Education'), ('Society', 'Society'), ('History', 'History'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Economics', 'Economics'), ('Travel', 'Travel'), ('Style', 'Style'), ('Health', 'Health')], default='World', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('excerpt', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
